export { default as Envelope } from './envelope.svg'
export { default as Lock } from './lock.svg'
export { default as User } from './user.svg'
export { default as Eye } from './eye.svg'
export { default as Pen } from './pen.svg'
export { default as Signout } from './signout.svg'
export { default as Cover } from './cover.svg'
export { default as Upload } from './upload.svg'
